export const SET_DISPLAY: "SET_DISPLAY" = "SET_DISPLAY";
export const REMOVE_DISPLAY: "REMOVE_DISPLAY" = "REMOVE_DISPLAY";
export const ADD_PAD: "ADD_PAD" = "ADD_PAD";
export const PLACE_PAD_BEFORE: "PLACE_PAD_BEFORE" = "PLACE_PAD_BEFORE";
export const PLACE_PAD_AFTER: "PLACE_PAD_AFTER" = "PLACE_PAD_AFTER";
export const REMOVE_PAD: "REMOVE_PAD" = "REMOVE_PAD";
export const SWAP_PADS: "SWAP_PADS" = "SWAP_PADS";
